import { MAP_SIZE, TELECOM_EXTRA_SEARCH_TURNS } from "./constants.ts";
import { getLocation, getNeighbors, isSamePosition } from "./grid.ts";
import type {
  DestructionLevel,
  GameState,
  LocationState,
  Position,
  TurnEvent,
} from "./types.ts";

/**
 * Apply one point of destruction to a location.
 * Returns the new destruction level and whether the location was just fully destroyed.
 */
export const addDestruction = (
  location: LocationState,
  amount: number,
): { newLevel: DestructionLevel; wasFullyDestroyed: boolean } => {
  const previousLevel = location.destruction;
  const newLevel = Math.min(3, location.destruction + amount) as DestructionLevel;
  location.destruction = newLevel;
  return { newLevel, wasFullyDestroyed: previousLevel < 3 && newLevel >= 3 };
};

/** Get location from grid, returning null if not found */
const locationAt = (state: GameState, position: Position): LocationState | undefined =>
  getLocation(state.grid, position) ?? undefined;

/**
 * Check and trigger special location effects when a location first takes damage.
 * Returns any events generated by the trigger.
 */
export const triggerSpecialEffect = (
  state: GameState,
  position: Position,
): TurnEvent[] => {
  const location = locationAt(state, position);
  if (!location?.special || location.specialTriggered) return [];

  location.specialTriggered = true;
  const events: TurnEvent[] = [];

  switch (location.special) {
    case "nuclear_plant":
      events.push({ event: "nuclear_meltdown" });
      events.push(...applyNuclearMeltdown(state, position));
      break;

    case "city_hall":
      events.push({ event: "city_hall_riots" });
      events.push(...applyCityHallRiots(state, position));
      break;

    case "telecom_tower":
      events.push({ event: "telecom_destroyed" });
      applyTelecomDestroyed(state);
      break;

    case "bridge":
      events.push({ event: "bridge_collapsed" });
      applyBridgeCollapse(state);
      break;

    case "mountains":
      events.push({ event: "mountain_home_destroyed" });
      state.player.temporaryDisadvantageRolls = 1;
      break;

    case "docks":
      // Docks has no special trigger effect
      break;
  }

  return events;
};

/** Check if player is killed by a fully destroyed location, pushing events if so */
const checkPlayerDeathByDestruction = (
  state: GameState,
  pos: Position,
  wasFullyDestroyed: boolean,
  events: TurnEvent[],
): void => {
  if (wasFullyDestroyed && isSamePosition(state.player.position, pos)) {
    state.player.status = "dead";
    state.player.deathCause = "killed_by_destruction";
    events.push({ event: "player_killed", cause: "killed_by_destruction" });
  }
};

/**
 * Apply area-of-effect destruction to a position and its neighbors.
 * Used by both nuclear meltdown and city hall riots with different amounts and cascade rules.
 */
const applyAreaDestruction = (
  state: GameState,
  position: Position,
  amount: number,
  excludeSpecial: string,
  cascadeOnlyFirstDamage: boolean,
): TurnEvent[] => {
  const events: TurnEvent[] = [];

  for (const pos of [position, ...getNeighbors(position)]) {
    const loc = locationAt(state, pos);
    if (!loc) continue;

    const prevDestruction = loc.destruction;
    const { newLevel, wasFullyDestroyed } = addDestruction(loc, amount);
    events.push({ event: "destruction", position: pos, newLevel });

    checkPlayerDeathByDestruction(state, pos, wasFullyDestroyed, events);

    const shouldCascade = loc.special && !loc.specialTriggered && loc.special !== excludeSpecial;
    if (shouldCascade && (!cascadeOnlyFirstDamage || prevDestruction === 0)) {
      events.push(...triggerSpecialEffect(state, pos));
    }
  }

  return events;
};

/** Nuclear meltdown: fully destroy this location and all neighbors */
const applyNuclearMeltdown = (state: GameState, position: Position): TurnEvent[] =>
  applyAreaDestruction(state, position, 3, "nuclear_plant", false);

/** City hall riots: add 1 destruction to this location and all neighbors */
const applyCityHallRiots = (state: GameState, position: Position): TurnEvent[] =>
  applyAreaDestruction(state, position, 1, "city_hall", true);

/** Telecom destroyed: add extra search turns */
const applyTelecomDestroyed = (state: GameState): void => {
  if (state.phase.phase === "searching_base") {
    state.phase.extraSearchTurns += TELECOM_EXTRA_SEARCH_TURNS;
  }
  // If still in finding_kaiju phase, the effect is stored and applied when searching begins
};

/** Bridge collapse: split the map, player must pick a side */
const applyBridgeCollapse = (state: GameState): void => {
  const CENTER_COL = Math.floor(MAP_SIZE / 2);
  const playerCol = state.player.position.col;

  if (playerCol < CENTER_COL) {
    state.bridge = { collapsed: true, playerSide: "west" };
  } else if (playerCol > CENTER_COL) {
    state.bridge = { collapsed: true, playerSide: "east" };
  } else {
    // Player is on the center column — must choose on next move
    state.bridge = { collapsed: true, playerSide: null, mustChoose: true };
  }
};

/** Apply single-point destruction to a location, returning events for damage, death, and cascades */
const destroyLocation = (
  state: GameState,
  location: LocationState,
  position: Position,
): TurnEvent[] => {
  const prevDestruction = location.destruction;
  const { newLevel, wasFullyDestroyed } = addDestruction(location, 1);
  const events: TurnEvent[] = [
    { event: "destruction", position, newLevel },
  ];

  checkPlayerDeathByDestruction(state, position, wasFullyDestroyed, events);

  if (prevDestruction === 0 && location.special && !location.specialTriggered) {
    events.push(...triggerSpecialEffect(state, position));
  }

  return events;
};

/**
 * Apply destruction from the kaiju entering a location.
 * Handles the destruction increment, special trigger check, and player death.
 */
export const applyKaijuDestruction = (state: GameState, position: Position): TurnEvent[] => {
  const location = locationAt(state, position);
  return location ? destroyLocation(state, location, position) : [];
};
